spring:
  application:
    name: spring-cloud-gcp-timed-issue
  threads:
    virtual:
      enabled: true

#Server configuration
server:
  shutdown: graceful
  error:
    include-message:
      always

management:
  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1
  metrics:
    tags:
      application: ${spring.application.name}
    enable:
      all: true
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,metrics,refresh,env,configprops,beans